IF((NOT WITH_CUDA) OR WIN32 OR APPLE)
  SET(NVTX_FOUND OFF)
  RETURN()
ENDIF()

SET(NVTX_ROOT "/usr" CACHE PATH "NVTX ROOT")
FIND_PATH(NVTX_INCLUDE_DIR nvToolsExt.h
  PATHS ${NVTX_ROOT} ${NVTX_ROOT}/include
  $ENV{NVTX_ROOT} $ENV{NVTX_ROOT}/include ${CUDA_TOOLKIT_INCLUDE}
  NO_DEFAULT_PATH
  )

GET_FILENAME_COMPONENT(__libpath_hint ${CUDA_CUDART_LIBRARY} PATH)

SET(TARGET_ARCH "x86_64")
IF(NOT ${CMAKE_SYSTEM_PROCESSOR})
  SET(TARGET_ARCH ${CMAKE_SYSTEM_PROCESSOR})
ENDIF()

LIST(APPEND NVTX_CHECK_LIBRARY_DIRS
    ${NVTX_ROOT}
    ${NVTX_ROOT}/lib64
    ${NVTX_ROOT}/lib
    ${NVTX_ROOT}/lib/${TARGET_ARCH}-linux-gnu
    $ENV{NVTX_ROOT}
    $ENV{NVTX_ROOT}/lib64
    $ENV{NVTX_ROOT}/lib
    ${CUDA_TOOLKIT_ROOT_DIR}
    ${CUDA_TOOLKIT_ROOT_DIR}/targets/${TARGET_ARCH}-linux/lib)

FIND_LIBRARY(CUDA_NVTX_LIB NAMES libnvToolsExt.so
    PATHS ${NVTX_CHECK_LIBRARY_DIRS} ${NVTX_INCLUDE_DIR} ${__libpath_hint}
    NO_DEFAULT_PATH
    DOC "Path to the NVTX library.")

IF(NVTX_INCLUDE_DIR AND CUDA_NVTX_LIB)
  SET(NVTX_FOUND ON)
ELSE()
  SET(NVTX_FOUND OFF)
ENDIF()

IF(NVTX_FOUND)
  INCLUDE_DIRECTORIES(${NVTX_INCLUDE_DIR})
  ADD_DEFINITIONS(-DCINN_WITH_NVTX)
ENDIF()
